### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by aremazeilles** [jamatics/pi_ctag#3]
Here is the list of topic I think we should progressively handle

- [x] add all `run_pi_x` in the root folder, like for the balance case
- [x] consider gathering all test_data in a common folder
- [ ] check input and output data format
- [x] add unit testing
- [x] add docker generation
- [ ] update template excel sheet
- [ ] verify data collected structure

**Comment by jamatics** [comment]
I click the second todo is it OK. @aremazeilles
